### ISSUE TITLE
namespace defaults to `jx` for remoteCluster environment

### ISSUE THREAD

**Issue by gazal-k** [jenkins-x/jx-promote#165]
The environment spec looks like:
```yaml
spec:
  kind: Permanent
  label: Qat1
  namespace: jx-qat1
  order: 500
  promotionStrategy: Auto
  remoteCluster: true
  source:
    ref: master
    url: https://github.com/org/env-org-qat1.git
```
But promotion PR to `env-org-qat1` always uses the namespace `jx`
```yaml
- chart: dev/jx3-node-demo-app
  version: 1.0.6
  name: jx3-node-demo-app
  namespace: jx
```
