### ISSUE TITLE
promotion to additional auto environments get the `do-not-merge/hold` label

### ISSUE THREAD

**Issue by gazal-k** [jenkins-x/jx-promote#166]
The first environment only gets an `env/` label. But additional environments also have `do-not-merge/hold` which essentially makes them non-auto even though their `promotionStrategy` is `Auto`

env specs:

```yaml
apiVersion: jenkins.io/v1
kind: Environment
  labels:
    env: staging
    gitops.jenkins-x.io/pipeline: namespaces
    team: jx
  name: staging
  namespace: jx
spec:
  kind: Permanent
  label: Staging
  namespace: jx-staging
  order: 100
  promotionStrategy: Auto
```

```yaml
apiVersion: jenkins.io/v1
kind: Environment
  labels:
    env: qat1
    gitops.jenkins-x.io/pipeline: namespaces
    team: jx
  name: qat1
  namespace: jx
spec:
  kind: Permanent
  label: Qat1
  namespace: jx-qat1
  order: 500
  promotionStrategy: Auto
  remoteCluster: true
  source:
    ref: master
    url: https://github.com/org/env-org-qat1.git
```

```yaml
apiVersion: jenkins.io/v1
kind: Environment
  labels:
    env: qat2
    gitops.jenkins-x.io/pipeline: namespaces
    team: jx
  name: qat2
  namespace: jx
spec:
  kind: Permanent
  label: Qat2
  namespace: jx-qat2
  order: 500
  promotionStrategy: Auto
  remoteCluster: true
  source:
    ref: master
    url: https://github.com/org/env-org-qat2.git
```

The PR on qat1 & qat2 has labels like:
![Screenshot from 2020-12-03 17-57-39](https://user-images.githubusercontent.com/8210299/100974820-0e37cc80-3591-11eb-9361-550237e05163.png)
