### ISSUE TITLE
set the OCI flag if promoting to a remote repository and OCI is enabled

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx-promote#351]
if OCI is enabled when promoting we should also set the `oci: true` in the modified helmfile

e.g. 
```yaml
repositories:
- name: dev
  url: harbor-jx.jx3.XXX/omvp-upstream
  oci: true
releases:
- chart: dev/ghttp
  version: 0.0.3
  name: ghttp
templates: {}
renderedvalues: {}
```
